language: python
python:
  - "2.7"
  # - "3.3"
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"

install:
  # Install Sublime Text and output version
  - curl http://rawgithub.com/twolfson/sublime-installer/0.1.1/install.sh | sh -s $SUBLIME_TEXT_VERSION
  - subl --version

  # Install `sublime_harness`
  - python setup.py develop

  # Install dev requirements
  - pip install -r requirements-dev.txt

script:
  # Run our tests
  # TODO: Verify via vagrant wtf is going on with Travis.
  # TODO: Verify this export statement works with tests
  - SUBLIME_AUTO_KILL=TRUE ./test.sh

notifications:
  email: false
